export interface WordPair {
  civilian: string;
  spy: string;
}

// Groq API — free tier, OpenAI-compatible, very fast.
// Get your free key at: https://console.groq.com
// Set GROQ_API_KEY in your .env.local and Vercel environment variables.
const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";

const SYSTEM_PROMPT = `You are a word-pair generator for a social deduction game called WordSpy.
Return ONLY a valid JSON object with exactly two keys: "civilian" and "spy".
No markdown, no explanation, no extra text — just the raw JSON object.`;

const USER_PROMPT = `Generate a word pair for the game. The civilian word and spy word must be:
- Common everyday nouns that most people know
- Related to each other (same category or domain) but distinct enough to cause confusion
- Not too obvious (avoid pairs like dog/cat) and not too obscure
 
Example outputs:
{"civilian":"piano","spy":"guitar"}
{"civilian":"swimming pool","spy":"lake"}
{"civilian":"hospital","spy":"clinic"}
 
Now generate a new unique pair:`;

const FALLBACK_WORD_PAIRS: WordPair[] = [
  { civilian: "piano", spy: "guitar" },
  { civilian: "swimming pool", spy: "lake" },
  { civilian: "coffee", spy: "tea" },
  { civilian: "airplane", spy: "helicopter" },
  { civilian: "hospital", spy: "clinic" },
  { civilian: "chess", spy: "checkers" },
  { civilian: "diamond", spy: "crystal" },
  { civilian: "passport", spy: "ID card" },
  { civilian: "submarine", spy: "boat" },
  { civilian: "telescope", spy: "binoculars" },
  { civilian: "library", spy: "bookstore" },
  { civilian: "motorcycle", spy: "bicycle" },
  { civilian: "prison", spy: "school" },
  { civilian: "volcano", spy: "mountain" },
  { civilian: "sushi", spy: "sashimi" },
  { civilian: "butter", spy: "margarine" },
  { civilian: "crocodile", spy: "alligator" },
  { civilian: "trumpet", spy: "trombone" },
  { civilian: "opera", spy: "musical" },
  { civilian: "kayak", spy: "canoe" },
  { civilian: "notebook", spy: "journal" },
  { civilian: "fork", spy: "spoon" },
  { civilian: "candle", spy: "lamp" },
  { civilian: "river", spy: "lake" },
  { civilian: "mountain", spy: "hill" },
  { civilian: "wallet", spy: "purse" },
  { civilian: "camera", spy: "binoculars" },
  { civilian: "helmet", spy: "hat" },
  { civilian: "blanket", spy: "towel" },
  { civilian: "soap", spy: "shampoo" },
  { civilian: "window", spy: "mirror" },
  { civilian: "clock", spy: "watch" },
  { civilian: "desk", spy: "table" },
  { civilian: "couch", spy: "bench" },
  { civilian: "painting", spy: "photograph" },
  { civilian: "socks", spy: "gloves" },
  { civilian: "ring", spy: "bracelet" },
  { civilian: "apple", spy: "pear" },
  { civilian: "orange", spy: "tangerine" },
  { civilian: "cake", spy: "pie" },
  { civilian: "burger", spy: "sandwich" },
  { civilian: "train", spy: "subway" },
  { civilian: "airport", spy: "station" },
  { civilian: "doctor", spy: "nurse" },
  { civilian: "teacher", spy: "professor" },
  { civilian: "pencil", spy: "marker" },
  { civilian: "eraser", spy: "sharpener" },
  { civilian: "cloud", spy: "fog" },
  { civilian: "storm", spy: "hurricane" },
  { civilian: "ocean", spy: "sea" },
  { civilian: "island", spy: "peninsula" },
  { civilian: "forest", spy: "jungle" },
  { civilian: "lion", spy: "tiger" },
  { civilian: "rabbit", spy: "hamster" },
  { civilian: "eagle", spy: "hawk" },
  { civilian: "boat", spy: "canoe" },
  { civilian: "ship", spy: "yacht" },
  { civilian: "phone", spy: "radio" },
  { civilian: "television", spy: "projector" },
  { civilian: "keyboard", spy: "typewriter" },
  { civilian: "printer", spy: "scanner" },
  { civilian: "battery", spy: "generator" },
  { civilian: "rocket", spy: "missile" },
  { civilian: "castle", spy: "palace" },
  { civilian: "church", spy: "chapel" },
  { civilian: "street", spy: "alley" },
  { civilian: "bridge", spy: "tunnel" },
  { civilian: "shirt", spy: "jacket" },
  { civilian: "shoes", spy: "boots" },
  { civilian: "belt", spy: "tie" },
  { civilian: "glasses", spy: "goggles" },
  { civilian: "bread", spy: "toast" },
  { civilian: "rice", spy: "pasta" },
  { civilian: "soup", spy: "stew" },
  { civilian: "salt", spy: "sugar" },
  { civilian: "violin", spy: "cello" },
  { civilian: "drum", spy: "tambourine" },
  { civilian: "book", spy: "magazine" },
  { civilian: "newspaper", spy: "flyer" },
  { civilian: "garden", spy: "park" },
  { civilian: "farm", spy: "ranch" },
  { civilian: "chef", spy: "baker" },
  { civilian: "waiter", spy: "bartender" },
  { civilian: "police", spy: "security" },
  { civilian: "firefighter", spy: "paramedic" },
  { civilian: "museum", spy: "library" },
  { civilian: "school", spy: "university" },
  { civilian: "battery charger", spy: "battery" },
  { civilian: "computer", spy: "tablet" },
  { civilian: "monitor", spy: "television" },
  { civilian: "mouse", spy: "trackpad" },
  { civilian: "hammer", spy: "wrench" },
  { civilian: "screwdriver", spy: "drill" },
  { civilian: "ladder", spy: "stairs" },
  { civilian: "tent", spy: "cabin" },
  { civilian: "beach", spy: "desert" },
  { civilian: "snow", spy: "hail" },
  { civilian: "raincoat", spy: "umbrella" },
  { civilian: "ticket", spy: "receipt" },
  { civilian: "mailbox", spy: "locker" },
  { civilian: "garage", spy: "warehouse" },
  { civilian: "fan", spy: "air conditioner" },
  { civilian: "refrigerator", spy: "freezer" },
  { civilian: "microwave", spy: "oven" },
  { civilian: "plate", spy: "tray" },
  { civilian: "cup", spy: "mug" },
  { civilian: "straw", spy: "spoon" },
  { civilian: "coin", spy: "token" },
  { civilian: "cash", spy: "voucher" },
  { civilian: "map", spy: "globe" },
  { civilian: "compass", spy: "GPS" },
  { civilian: "rope", spy: "chain" },
  { civilian: "lock", spy: "key" },
  { civilian: "brush", spy: "comb" },
  { civilian: "perfume", spy: "cologne" },
  { civilian: "refrigerator", spy: "cooler" },
  { civilian: "backpack", spy: "suitcase" },
  { civilian: "microscope", spy: "telescope" },
  { civilian: "helmet", spy: "hard hat" },
  { civilian: "notepad", spy: "clipboard" },
  { civilian: "garage", spy: "shed" },
  { civilian: "pillow", spy: "cushion" },
  { civilian: "curtain", spy: "blinds" },
  { civilian: "balcony", spy: "porch" },
  { civilian: "elevator", spy: "escalator" },
  { civilian: "flashlight", spy: "lantern" },
  { civilian: "battery", spy: "power bank" },
  { civilian: "vacuum", spy: "broom" },
  { civilian: "mop", spy: "broom" },
  { civilian: "sink", spy: "bathtub" },
  { civilian: "toothpaste", spy: "mouthwash" },
  { civilian: "toothbrush", spy: "razor" },
  { civilian: "sandals", spy: "slippers" },
  { civilian: "hoodie", spy: "sweater" },
  { civilian: "vest", spy: "jacket" },
  { civilian: "jeans", spy: "khakis" },
  { civilian: "scarf", spy: "shawl" },
  { civilian: "mittens", spy: "gloves" },
  { civilian: "earrings", spy: "necklace" },
  { civilian: "bracelet", spy: "anklet" },
  { civilian: "pancake", spy: "waffle" },
  { civilian: "biscuit", spy: "cookie" },
  { civilian: "muffin", spy: "cupcake" },
  { civilian: "jam", spy: "jelly" },
  { civilian: "noodles", spy: "spaghetti" },
  { civilian: "dumpling", spy: "meatball" },
  { civilian: "burrito", spy: "wrap" },
  { civilian: "sausage", spy: "hotdog" },
  { civilian: "lemon", spy: "lime" },
  { civilian: "peach", spy: "nectarine" },
  { civilian: "grape", spy: "blueberry" },
  { civilian: "cabbage", spy: "lettuce" },
  { civilian: "spinach", spy: "kale" },
  { civilian: "pickle", spy: "cucumber" },
  { civilian: "cupboard", spy: "drawer" },
  { civilian: "pan", spy: "skillet" },
  { civilian: "pot", spy: "kettle" },
  { civilian: "blender", spy: "mixer" },
  { civilian: "toaster", spy: "grill" },
  { civilian: "napkin", spy: "tissue" },
  { civilian: "bucket", spy: "basket" },
  { civilian: "crate", spy: "box" },
  { civilian: "fence", spy: "wall" },
  { civilian: "gate", spy: "door" },
  { civilian: "sidewalk", spy: "pathway" },
  { civilian: "highway", spy: "freeway" },
  { civilian: "taxi", spy: "bus" },
  { civilian: "tram", spy: "subway" },
  { civilian: "skateboard", spy: "scooter" },
  { civilian: "roller skates", spy: "ice skates" },
  { civilian: "canoe", spy: "raft" },
  { civilian: "harbor", spy: "dock" },
  { civilian: "compass", spy: "map" },
  { civilian: "calendar", spy: "schedule" },
  { civilian: "alarm", spy: "timer" },
  { civilian: "speaker", spy: "microphone" },
  { civilian: "headphones", spy: "earbuds" },
  { civilian: "remote", spy: "controller" },
  { civilian: "router", spy: "modem" },
  { civilian: "website", spy: "application" },
  { civilian: "password", spy: "PIN" },
  { civilian: "folder", spy: "binder" },
  { civilian: "stapler", spy: "tape" },
  { civilian: "envelope", spy: "package" },
  { civilian: "receipt", spy: "invoice" },
  { civilian: "receipt", spy: "ticket" },
  { civilian: "calendar", spy: "planner" },
  { civilian: "medal", spy: "trophy" },
  { civilian: "statue", spy: "monument" },
  { civilian: "fountain", spy: "waterfall" },
  { civilian: "cave", spy: "tunnel" },
  { civilian: "desert", spy: "savanna" },
  { civilian: "swamp", spy: "marsh" },
  { civilian: "reef", spy: "island" },
  { civilian: "wolf", spy: "fox" },
  { civilian: "goat", spy: "sheep" },
  { civilian: "donkey", spy: "horse" },
  { civilian: "seal", spy: "otter" },
  { civilian: "shrimp", spy: "lobster" },
  { civilian: "crab", spy: "lobster" },
  { civilian: "parrot", spy: "canary" },
  { civilian: "owl", spy: "hawk" },
  { civilian: "bee", spy: "wasp" },
  { civilian: "ant", spy: "termite" },
  { civilian: "webcam", spy: "camera" },
  { civilian: "microphone", spy: "speaker" },
  { civilian: "projector", spy: "monitor" },
  { civilian: "generator", spy: "engine" },
  { civilian: "engine", spy: "motor" },
  { civilian: "tractor", spy: "bulldozer" },
  { civilian: "chainsaw", spy: "axe" },
  { civilian: "pliers", spy: "tongs" },
  { civilian: "needle", spy: "pin" },
  { civilian: "thread", spy: "string" },
  { civilian: "magnet", spy: "battery" },
  { civilian: "soap", spy: "detergent" },
  { civilian: "sunscreen", spy: "lotion" },
  { civilian: "wallet", spy: "billfold" },
  { civilian: "briefcase", spy: "suitcase" },
  { civilian: "crown", spy: "tiara" },
  { civilian: "throne", spy: "chair" },
  { civilian: "torch", spy: "flashlight" },
  { civilian: "tent", spy: "canopy" },
  { civilian: "campfire", spy: "fireplace" },
  { civilian: "binoculars", spy: "periscope" },
  { civilian: "whistle", spy: "flute" },
  { civilian: "accordion", spy: "harmonica" },
  { civilian: "ukulele", spy: "guitar" },
  { civilian: "microphone", spy: "megaphone" },
  { civilian: "comic", spy: "magazine" },
  { civilian: "poster", spy: "banner" },
  { civilian: "stamp", spy: "sticker" },
  { civilian: "puzzle", spy: "maze" },
  { civilian: "dice", spy: "dominoes" },
  { civilian: "helmet", spy: "mask" },
  { civilian: "statue", spy: "sculpture" },
  { civilian: "aquarium", spy: "terrarium" },
  { civilian: "greenhouse", spy: "garden" },
  { civilian: "bakery", spy: "cafe" },
  { civilian: "pharmacy", spy: "clinic" },
  { civilian: "market", spy: "mall" },
  { civilian: "stadium", spy: "arena" },
  { civilian: "gym", spy: "dojo" },
  { civilian: "theater", spy: "cinema" },
  { civilian: "circus", spy: "carnival" },
  { civilian: "lighthouse", spy: "watchtower" },
  { civilian: "barn", spy: "stable" },
  { civilian: "chimney", spy: "vent" },
  { civilian: "attic", spy: "basement" },
  { civilian: "hallway", spy: "corridor" },
  { civilian: "air fryer", spy: "oven" },
  { civilian: "thermos", spy: "water bottle" },
  { civilian: "pitcher", spy: "jug" },
  { civilian: "ladle", spy: "spatula" },
  { civilian: "colander", spy: "strainer" },
  { civilian: "cutting board", spy: "tray" },
  { civilian: "apron", spy: "uniform" },
  { civilian: "locker", spy: "cabinet" },
  { civilian: "bookshelf", spy: "cupboard" },
  { civilian: "nightstand", spy: "dresser" },
  { civilian: "beanbag", spy: "cushion" },
  { civilian: "hammock", spy: "swing" },
  { civilian: "ceiling fan", spy: "ventilator" },
  { civilian: "thermometer", spy: "barometer" },
  { civilian: "calculator", spy: "keyboard" },
  { civilian: "clipboard", spy: "folder" },
  { civilian: "highlighter", spy: "marker" },
  { civilian: "chalk", spy: "crayon" },
  { civilian: "whiteboard", spy: "blackboard" },
  { civilian: "bookmark", spy: "sticky note" },
  { civilian: "backpack", spy: "duffel bag" },
  { civilian: "suitcase", spy: "briefcase" },
  { civilian: "wallet", spy: "coin purse" },
  { civilian: "helmet", spy: "visor" },
  { civilian: "rain boots", spy: "galoshes" },
  { civilian: "slippers", spy: "sandals" },
  { civilian: "raincoat", spy: "poncho" },
  { civilian: "blazer", spy: "coat" },
  { civilian: "cardigan", spy: "hoodie" },
  { civilian: "overalls", spy: "jumpsuit" },
  { civilian: "mittens", spy: "oven mitts" },
  { civilian: "necklace", spy: "locket" },
  { civilian: "watch", spy: "bracelet" },
  { civilian: "omelet", spy: "scrambled eggs" },
  { civilian: "pudding", spy: "custard" },
  { civilian: "brownie", spy: "cake" },
  { civilian: "pretzel", spy: "bagel" },
  { civilian: "waffle", spy: "pancake" },
  { civilian: "lasagna", spy: "casserole" },
  { civilian: "ramen", spy: "noodles" },
  { civilian: "meatball", spy: "dumpling" },
  { civilian: "bacon", spy: "ham" },
  { civilian: "smoothie", spy: "milkshake" },
  { civilian: "soda", spy: "sparkling water" },
  { civilian: "coconut", spy: "pineapple" },
  { civilian: "blueberry", spy: "blackberry" },
  { civilian: "raspberry", spy: "strawberry" },
  { civilian: "lettuce", spy: "cabbage" },
  { civilian: "zucchini", spy: "cucumber" },
  { civilian: "pumpkin", spy: "squash" },
  { civilian: "onion", spy: "shallot" },
  { civilian: "garlic", spy: "ginger" },
  { civilian: "pepper", spy: "paprika" },
  { civilian: "canoe", spy: "kayak" },
  { civilian: "ferry", spy: "ship" },
  { civilian: "jet ski", spy: "speedboat" },
  { civilian: "van", spy: "minibus" },
  { civilian: "pickup truck", spy: "truck" },
  { civilian: "convertible", spy: "coupe" },
  { civilian: "scooter", spy: "moped" },
  { civilian: "subway", spy: "train" },
  { civilian: "crosswalk", spy: "intersection" },
  { civilian: "traffic light", spy: "street lamp" },
  { civilian: "billboard", spy: "signboard" },
  { civilian: "compass", spy: "sextant" },
  { civilian: "stopwatch", spy: "timer" },
  { civilian: "calendar", spy: "agenda" },
  { civilian: "headset", spy: "headphones" },
  { civilian: "earbuds", spy: "hearing aid" },
  { civilian: "microchip", spy: "circuit board" },
  { civilian: "USB drive", spy: "memory card" },
  { civilian: "tablet", spy: "e-reader" },
  { civilian: "router", spy: "switch" },
  { civilian: "charger", spy: "adapter" },
  { civilian: "extension cord", spy: "power strip" },
  { civilian: "flash drive", spy: "external hard drive" },
  { civilian: "joystick", spy: "controller" },
  { civilian: "arcade machine", spy: "slot machine" },
  { civilian: "tent", spy: "teepee" },
  { civilian: "campfire", spy: "bonfire" },
  { civilian: "lantern", spy: "flashlight" },
  { civilian: "binoculars", spy: "scope" },
  { civilian: "fishing rod", spy: "harpoon" },
  { civilian: "lifeboat", spy: "raft" },
  { civilian: "igloo", spy: "hut" },
  { civilian: "cabin", spy: "cottage" },
  { civilian: "volleyball", spy: "beach ball" },
  { civilian: "baseball bat", spy: "club" },
  { civilian: "helmet", spy: "face shield" },
  { civilian: "trophy", spy: "plaque" },
  { civilian: "medal", spy: "badge" },
  { civilian: "whistle", spy: "horn" },
  { civilian: "referee", spy: "umpire" },
  { civilian: "backpack", spy: "satchel" },
  { civilian: "briefcase", spy: "portfolio" },
  { civilian: "newspaper", spy: "newsletter" },
  { civilian: "novel", spy: "textbook" },
  { civilian: "dictionary", spy: "encyclopedia" },
  { civilian: "poster", spy: "flyer" },
  { civilian: "ticket", spy: "pass" },
  { civilian: "passport", spy: "visa" },
  { civilian: "receipt", spy: "coupon" },
  { civilian: "invoice", spy: "bill" },
  { civilian: "badge", spy: "sticker" },
  { civilian: "globe", spy: "map" },
  { civilian: "statue", spy: "bust" },
  { civilian: "painting", spy: "mural" },
  { civilian: "fountain", spy: "geyser" },
  { civilian: "tower", spy: "skyscraper" },
  { civilian: "lighthouse", spy: "beacon" },
  { civilian: "tentacle", spy: "tail" },
  { civilian: "claw", spy: "fang" },
  { civilian: "horn", spy: "antler" },
  { civilian: "camel", spy: "llama" },
  { civilian: "goose", spy: "duck" },
  { civilian: "falcon", spy: "eagle" },
  { civilian: "jellyfish", spy: "octopus" },
  { civilian: "dolphin", spy: "shark" },
  { civilian: "penguin", spy: "puffin" },
  { civilian: "cricket", spy: "grasshopper" },
  { civilian: "dragonfly", spy: "mosquito" },
  { civilian: "spider", spy: "scorpion" },
  { civilian: "beehive", spy: "anthill" },
  { civilian: "cocoon", spy: "nest" },
  { civilian: "mirror", spy: "window" },
  { civilian: "doormat", spy: "rug" },
  { civilian: "chimney", spy: "smokestack" },
  { civilian: "garage", spy: "carport" },
  { civilian: "faucet", spy: "hose" },
  { civilian: "drain", spy: "gutter" },
  { civilian: "bucket", spy: "pail" },
  { civilian: "sponge", spy: "cloth" },
  { civilian: "soap dispenser", spy: "sanitizer bottle" },
  { civilian: "detergent", spy: "bleach" },
  { civilian: "hanger", spy: "hook" },
  { civilian: "clothespin", spy: "clip" },
  { civilian: "alarm clock", spy: "stopwatch" },
  { civilian: "safe", spy: "vault" },
  { civilian: "keychain", spy: "lanyard" },
  { civilian: "stamp", spy: "seal" },
  { civilian: "magnifying glass", spy: "microscope" },
  { civilian: "tripod", spy: "easel" },
  { civilian: "megaphone", spy: "speaker" },
  { civilian: "drone", spy: "helicopter" },
  { civilian: "satellite", spy: "space station" },
  { civilian: "planet", spy: "moon" },
  { civilian: "comet", spy: "meteor" },
  { civilian: "asteroid", spy: "meteorite" },
];

function getFallbackWordPair(): WordPair {
  return FALLBACK_WORD_PAIRS[Math.floor(Math.random() * FALLBACK_WORD_PAIRS.length)]
}
 
async function generateFromGroq(apiKey: string): Promise<WordPair> {
  const response = await fetch(GROQ_API_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: 'llama-3.1-8b-instant', // fast, free, more than capable for this task
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: USER_PROMPT },
      ],
      temperature: 1.2,      // higher = more variety in word pairs
      max_tokens: 60,        // word pairs are tiny — no need for more
      stream: false,
    }),
  })
 
  if (!response.ok) {
    const err = await response.text()
    throw new Error(`Groq API error ${response.status}: ${err}`)
  }
 
  const data = await response.json()
  const rawText: string = data.choices?.[0]?.message?.content?.trim() ?? ''
 
  if (!rawText) {
    throw new Error(`Empty response from Groq. Full: ${JSON.stringify(data).slice(0, 300)}`)
  }
 
  console.log('Groq raw response:', rawText)
 
  // Try direct JSON parse first
  try {
    const pair = JSON.parse(rawText) as WordPair
    if (pair.civilian && pair.spy) return pair
  } catch { /* fall through to extraction */ }
 
  // Extract JSON object from response if there's any surrounding text
  const match = rawText.match(/\{[\s\S]*?\}/)
  if (match) {
    try {
      const pair = JSON.parse(match[0]) as WordPair
      if (pair.civilian && pair.spy) return pair
    } catch { /* fall through to error */ }
  }
 
  throw new Error(`Could not parse word pair from Groq response: ${rawText}`)
}
 
export async function generateWordPair(): Promise<WordPair> {
  const apiKey = process.env.GROQ_API_KEY
  const useFallback = process.env.USE_FALLBACK_WORDS === 'true'
 
  if (useFallback) {
    console.log('USE_FALLBACK_WORDS=true — using fallback word pair')
    return getFallbackWordPair()
  }
 
  if (!apiKey) {
    throw new Error('GROQ_API_KEY is not set and USE_FALLBACK_WORDS is not true')
  }
 
  try {
    return await generateFromGroq(apiKey)
  } catch (e) {
    console.error('Groq word generation failed:', (e as Error).message)
    // Graceful fallback so a Groq hiccup doesn't break the whole game start
    console.warn('Falling back to static word pairs')
    return getFallbackWordPair()
  }
}